// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Technical_Challenge.Infrastructure.Persistence.Context;

#nullable disable

namespace Technical_Challenge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Technical_Challenge.Domain.Entities.CurrencyQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ask")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bid");

                    b.Property<DateTime>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("currency");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_quotes_captured_at");

                    b.HasIndex("Currency")
                        .HasDatabaseName("idx_quotes_currency");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Technical_Challenge.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
